name: SDLC Assessment Scope

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run NCC SDLC Assessment Scope
        uses: TheTemplateFactory/github-action@main
        with:
          directory: '.'  # Optional: specify directories to analyze
          filter: '*.py,*.js,*.ts'  # Optional: filter specific file types

      - name: Upload Assessment Report
        uses: actions/upload-artifact@v4
        with:
          name: NCC-SDLC-Assessment-Scope
          path: NCC-SDLC-Assessment-Scope.zip
          retention-days: 30
